import type { BillTemplate } from "@/types/bill";

export const templates: BillTemplate[] = [
  {
    id: "standard-invoice",
    name: "Standard Invoice",
    description: "A clean, professional invoice suitable for any business",
    category: "invoice",
    icon: "FileText",
    showTax: true,
    showDiscount: true,
    showShipping: false,
    showDueDate: true,
    showHsnCode: false,
    showGstin: false,
    defaultCurrency: "USD",
    fields: [],
  },
  {
    id: "gst-invoice",
    name: "GST Invoice",
    description: "Tax invoice compliant with Indian GST requirements",
    category: "invoice",
    icon: "IndianRupee",
    showTax: true,
    showDiscount: true,
    showShipping: true,
    showDueDate: true,
    showHsnCode: true,
    showGstin: true,
    defaultCurrency: "INR",
    fields: [],
  },
  {
    id: "proforma-invoice",
    name: "Proforma Invoice",
    description: "Preliminary bill of sale sent before delivery of goods/services",
    category: "invoice",
    icon: "ClipboardList",
    showTax: true,
    showDiscount: true,
    showShipping: true,
    showDueDate: false,
    showHsnCode: false,
    showGstin: false,
    defaultCurrency: "USD",
    fields: [],
  },
  {
    id: "receipt",
    name: "Payment Receipt",
    description: "Acknowledge receipt of payment from a customer",
    category: "receipt",
    icon: "Receipt",
    showTax: false,
    showDiscount: false,
    showShipping: false,
    showDueDate: false,
    showHsnCode: false,
    showGstin: false,
    defaultCurrency: "USD",
    fields: [],
  },
  {
    id: "quotation",
    name: "Quotation / Estimate",
    description: "Provide a cost estimate before the actual sale",
    category: "quotation",
    icon: "Calculator",
    showTax: true,
    showDiscount: true,
    showShipping: true,
    showDueDate: false,
    showHsnCode: false,
    showGstin: false,
    defaultCurrency: "USD",
    fields: [],
  },
  {
    id: "delivery-challan",
    name: "Delivery Challan",
    description: "Document for shipment of goods without an invoice",
    category: "other",
    icon: "Truck",
    showTax: false,
    showDiscount: false,
    showShipping: false,
    showDueDate: false,
    showHsnCode: true,
    showGstin: true,
    defaultCurrency: "INR",
    fields: [],
  },
  {
    id: "credit-note",
    name: "Credit Note",
    description: "Issue a credit note for returned goods or billing corrections",
    category: "other",
    icon: "RotateCcw",
    showTax: true,
    showDiscount: false,
    showShipping: false,
    showDueDate: false,
    showHsnCode: false,
    showGstin: true,
    defaultCurrency: "INR",
    fields: [],
  },
  {
    id: "freelancer-invoice",
    name: "Freelancer Invoice",
    description: "Simple invoice perfect for freelancers and consultants",
    category: "invoice",
    icon: "UserCircle",
    showTax: true,
    showDiscount: false,
    showShipping: false,
    showDueDate: true,
    showHsnCode: false,
    showGstin: false,
    defaultCurrency: "USD",
    fields: [],
  },
];

export function getTemplate(id: string): BillTemplate | undefined {
  return templates.find((t) => t.id === id);
}
