import type { BillTemplate } from "@/types/bill";

export const templates: BillTemplate[] = [
  {
    id: "standard-invoice",
    name: "Standard Invoice",
    description: "A clean, professional invoice suitable for any business",
    category: "invoice",
    icon: "FileText",
    showTax: true,
    showDiscount: true,
    showShipping: false,
    showDueDate: true,
    showHsnCode: false,
    showGstin: false,
    defaultCurrency: "USD",
    fields: [],
  },
  {
    id: "gst-invoice",
    name: "GST Invoice",
    description: "Tax invoice compliant with Indian GST requirements",
    category: "invoice",
    icon: "IndianRupee",
    showTax: true,
    showDiscount: true,
    showShipping: true,
    showDueDate: true,
    showHsnCode: true,
    showGstin: true,
    defaultCurrency: "INR",
    fields: [],
  },
  {
    id: "proforma-invoice",
    name: "Proforma Invoice",
    description: "Preliminary bill of sale sent before delivery of goods/services",
    category: "invoice",
    icon: "ClipboardList",
    showTax: true,
    showDiscount: true,
    showShipping: true,
    showDueDate: false,
    showHsnCode: false,
    showGstin: false,
    defaultCurrency: "USD",
    fields: [],
  },
  {
    id: "receipt",
    name: "Payment Receipt",
    description: "Acknowledge receipt of payment from a customer",
    category: "receipt",
    icon: "Receipt",
    showTax: false,
    showDiscount: false,
    showShipping: false,
    showDueDate: false,
    showHsnCode: false,
    showGstin: false,
    defaultCurrency: "USD",
    fields: [],
  },
  {
    id: "quotation",
    name: "Quotation / Estimate",
    description: "Provide a cost estimate before the actual sale",
    category: "quotation",
    icon: "Calculator",
    showTax: true,
    showDiscount: true,
    showShipping: true,
    showDueDate: false,
    showHsnCode: false,
    showGstin: false,
    defaultCurrency: "USD",
    fields: [],
  },
  {
    id: "delivery-challan",
    name: "Delivery Challan",
    description: "Document for shipment of goods without an invoice",
    category: "other",
    icon: "Truck",
    showTax: false,
    showDiscount: false,
    showShipping: false,
    showDueDate: false,
    showHsnCode: true,
    showGstin: true,
    defaultCurrency: "INR",
    fields: [],
  },
  {
    id: "credit-note",
    name: "Credit Note",
    description: "Issue a credit note for returned goods or billing corrections",
    category: "other",
    icon: "RotateCcw",
    showTax: true,
    showDiscount: false,
    showShipping: false,
    showDueDate: false,
    showHsnCode: false,
    showGstin: true,
    defaultCurrency: "INR",
    fields: [],
  },
  {
    id: "freelancer-invoice",
    name: "Freelancer Invoice",
    description: "Simple invoice perfect for freelancers and consultants",
    category: "invoice",
    icon: "UserCircle",
    showTax: true,
    showDiscount: false,
    showShipping: false,
    showDueDate: true,
    showHsnCode: false,
    showGstin: false,
    defaultCurrency: "USD",
    fields: [],
  },
  {
    id: "rent-receipt",
    name: "Rent Receipt",
    description: "Monthly rent payment receipt for landlords and tenants",
    category: "receipt",
    icon: "Home",
    showTax: false,
    showDiscount: false,
    showShipping: false,
    showDueDate: false,
    showHsnCode: false,
    showGstin: false,
    defaultCurrency: "INR",
    fields: [],
  },
  {
    id: "shopping-receipt",
    name: "Shopping Receipt",
    description: "Retail shopping receipt for stores, supermarkets, and shops",
    category: "receipt",
    icon: "ShoppingBag",
    showTax: true,
    showDiscount: true,
    showShipping: false,
    showDueDate: false,
    showHsnCode: false,
    showGstin: false,
    defaultCurrency: "INR",
    fields: [],
  },
  {
    id: "subscription-invoice",
    name: "Subscription Invoice",
    description: "Recurring billing invoice for SaaS, memberships, and subscriptions",
    category: "invoice",
    icon: "RefreshCw",
    showTax: true,
    showDiscount: true,
    showShipping: false,
    showDueDate: true,
    showHsnCode: false,
    showGstin: false,
    defaultCurrency: "USD",
    fields: [],
  },
  {
    id: "purchase-order",
    name: "Purchase Order",
    description: "Official purchase order document for procurement and buying",
    category: "other",
    icon: "ShoppingCart",
    showTax: true,
    showDiscount: true,
    showShipping: true,
    showDueDate: true,
    showHsnCode: false,
    showGstin: false,
    defaultCurrency: "USD",
    fields: [],
  },
  {
    id: "expense-report",
    name: "Expense Report",
    description: "Employee expense claim report for reimbursement",
    category: "other",
    icon: "Wallet",
    showTax: false,
    showDiscount: false,
    showShipping: false,
    showDueDate: false,
    showHsnCode: false,
    showGstin: false,
    defaultCurrency: "USD",
    fields: [],
  },
  {
    id: "donation-receipt",
    name: "Donation Receipt",
    description: "Tax-deductible donation receipt for charities and nonprofits",
    category: "receipt",
    icon: "Heart",
    showTax: false,
    showDiscount: false,
    showShipping: false,
    showDueDate: false,
    showHsnCode: false,
    showGstin: false,
    defaultCurrency: "INR",
    fields: [],
  },
  {
    id: "service-invoice",
    name: "Service Invoice",
    description: "Professional service invoice for agencies, plumbers, electricians, and more",
    category: "invoice",
    icon: "Wrench",
    showTax: true,
    showDiscount: true,
    showShipping: false,
    showDueDate: true,
    showHsnCode: false,
    showGstin: false,
    defaultCurrency: "INR",
    fields: [],
  },
  {
    id: "export-invoice",
    name: "Export Invoice",
    description: "International export invoice with customs and shipping details",
    category: "invoice",
    icon: "Globe",
    showTax: true,
    showDiscount: true,
    showShipping: true,
    showDueDate: true,
    showHsnCode: true,
    showGstin: true,
    defaultCurrency: "USD",
    fields: [],
  },
];

export function getTemplate(id: string): BillTemplate | undefined {
  return templates.find((t) => t.id === id);
}
